import { Canvas } from '@react-three/fiber';
import { useGLTF, Stage, OrbitControls } from '@react-three/drei';

function Model({ url }) {
  // Loads the USDZ or GLB generated by the Python backend
  const { scene } = useGLTF(url);
  return <primitive object={scene} />;
}

export default function TwinViewer({ twinUrl }) {
  return (
    <div className="h-[500px] w-full bg-slate-900 rounded-xl overflow-hidden">
      <Canvas shadows dpr={[1, 2]} camera={{ fov: 50 }}>
        <Stage environment="city" intensity={0.6}>
          <Model url={twinUrl} />
        </Stage>
        <OrbitControls autoRotate />
      </Canvas>
      <div className="overlay">
        <h3>Live Cortisol Levels: <span className="text-green-400">Stable</span></h3>
      </div>
    </div>
  );
}