# cloudbuild.yaml
# Cloud Build configuration for IHEP application

steps:
  # Step 1: Install dependencies and run tests for frontend
  - name: 'node:18'
    id: 'frontend-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run lint
        npm run test:ci
        npm run build
    waitFor: ['-']

  # Step 2: Build and test Auth API
  - name: 'python:3.11'
    id: 'auth-api-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd services/auth-api
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pytest tests/ --cov=. --cov-report=xml
    env:
      - 'PYTHONPATH=/workspace/services/auth-api'
    waitFor: ['-']

  # Step 3: Build and test Health API
  - name: 'python:3.11'
    id: 'health-api-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd services/health-api
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pytest tests/ --cov=. --cov-report=xml
    waitFor: ['-']

  # Step 4: Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend-build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend/'
    waitFor: ['frontend-test']

  # Step 5: Build Auth API Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'auth-api-build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-auth-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-auth-api:latest'
      - '-f'
      - 'services/auth-api/Dockerfile'
      - 'services/auth-api/'
    waitFor: ['auth-api-test']

  # Step 6: Build Health API Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'health-api-build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-health-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-health-api:latest'
      - '-f'
      - 'services/health-api/Dockerfile'
      - 'services/health-api/'
    waitFor: ['health-api-test']

  # Step 7: Build Chat API Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'chat-api-build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-chat-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ihep-chat-api:latest'
      - '-f'
      - 'services/chat-api/Dockerfile'
      - 'services/chat-api/'
    waitFor: ['-']

  # Step 8: Push all images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push gcr.io/$PROJECT_ID/ihep-frontend:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/ihep-frontend:latest
        docker push gcr.io/$PROJECT_ID/ihep-auth-api:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/ihep-auth-api:latest
        docker push gcr.io/$PROJECT_ID/ihep-health-api:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/ihep-health-api:latest
        docker push gcr.io/$PROJECT_ID/ihep-chat-api:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/ihep-chat-api:latest
    waitFor:
      - 'frontend-build'
      - 'auth-api-build'
      - 'health-api-build'
      - 'chat-api-build'

  # Step 9: Deploy to Cloud Run (Blue-Green strategy)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-services'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy frontend
        gcloud run deploy ihep-frontend \
          --image gcr.io/$PROJECT_ID/ihep-frontend:$SHORT_SHA \
          --region $_REGION \
          --platform managed \
          --no-traffic \
          --tag blue-$SHORT_SHA
        
        # Deploy Auth API
        gcloud run deploy ihep-auth-api \
          --image gcr.io/$PROJECT_ID/ihep-auth-api:$SHORT_SHA \
          --region $_REGION \
          --platform managed \
          --no-traffic \
          --tag blue-$SHORT_SHA
        
        # Deploy Health API
        gcloud run deploy ihep-health-api \
          --image gcr.io/$PROJECT_ID/ihep-health-api:$SHORT_SHA \
          --region $_REGION \
          --platform managed \
          --no-traffic \
          --tag blue-$SHORT_SHA
        
        # Deploy Chat API
        gcloud run deploy ihep-chat-api \
          --image gcr.io/$PROJECT_ID/ihep-chat-api:$SHORT_SHA \
          --region $_REGION \
          --platform managed \
          --no-traffic \
          --tag blue-$SHORT_SHA
    waitFor: ['push-images']

  # Step 10: Run integration tests against new deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'integration-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get service URLs with blue tag
        FRONTEND_URL=$(gcloud run services describe ihep-frontend --region $_REGION --format 'value(status.url)')
        AUTH_URL=$(gcloud run services describe ihep-auth-api --region $_REGION --format 'value(status.url)')
        
        # Run integration tests
        # (Would execute comprehensive test suite here)
        echo "Running integration tests against blue deployment..."
        
        # Placeholder for actual tests
        curl -f "$FRONTEND_URL/health" || exit 1
        curl -f "$AUTH_URL/health" || exit 1
    waitFor: ['deploy-services']

  # Step 11: Gradual traffic migration (Blue-Green cutover)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'traffic-migration'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Migrate traffic gradually: 10% -> 50% -> 100%
        echo "Migrating 10% traffic to new revision..."
        gcloud run services update-traffic ihep-frontend \
          --region $_REGION \
          --to-tags blue-$SHORT_SHA=10
        
        sleep 300  # Wait 5 minutes, monitor metrics
        
        echo "Migrating 50% traffic to new revision..."
        gcloud run services update-traffic ihep-frontend \
          --region $_REGION \
          --to-tags blue-$SHORT_SHA=50
        
        sleep 300  # Wait 5 minutes, monitor metrics
        
        echo "Migrating 100% traffic to new revision..."
        gcloud run services update-traffic ihep-frontend \
          --region $_REGION \
          --to-latest
        
        # Update API services
        gcloud run services update-traffic ihep-auth-api \
          --region $_REGION \
          --to-latest
        
        gcloud run services update-traffic ihep-health-api \
          --region $_REGION \
          --to-latest
        
        gcloud run services update-traffic ihep-chat-api \
          --region $_REGION \
          --to-latest
    waitFor: ['integration-tests']

  # Step 12: Run database migrations if needed
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'database-migration'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f "database/migrations/$SHORT_SHA.sql" ]; then
          echo "Running database migration for $SHORT_SHA..."
          gcloud sql connect ihep-postgres-prod --user=postgres < database/migrations/$SHORT_SHA.sql
        else
          echo "No database migration needed"
        fi
    waitFor: ['traffic-migration']

# Trigger configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
timeout: '3600s'  # 60 minute timeout for entire pipeline

substitutions:
  _REGION: 'us-central1'

# Store build artifacts
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts'
    paths:
      - 'frontend/coverage/**'
      - 'services/*/coverage/**'