apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ihep-web
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/max-scale: "100"
        run.googleapis.com/min-scale: "1"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/ihep-web:latest
        ports:
        - name: http1
          containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: NEXTAUTH_SECRET
              key: latest
        - name: NEXTAUTH_URL
          value: "https://ihep-web-HASH-uc.a.run.app"
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 30
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3